/*
Filename:           dlg_c_main
System:             Dynamic Dialog System (Configuration Script)
Author:             Sherincall (Sherincall@gmail.com)
Date Created:       March 20, 2009
Summary:
Contains constants for customizing the Dynamic Dialog System.

Copyright (c) 2004 Paul Speed - BSD licensed.
NWN Tools - http://nwntools.sf.net/
Additions and changes from original copyright (c) 2005-2006 Greyhawk0


Revision Info should only be included for post-release revisions.
-----------------
Revision Date:
Revision Author:
Revision Summary:

*/

#include "ss_i_text"

////////////////////////////////////////////////////////////////////////////////
//  The default label for the autogenerated response "Next Page". This response
// will only be visible when the response list grows too large.
//
const string DLG_DEFAULTLABEL_NEXT = "Next Page";
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default label for the autogenerated response "Previous Page". This
// response will only be visible when the response list grows too large and
// the player has navigated to page 2 or higher.
//
const string DLG_DEFAULTLABEL_PREV = "Previous Page";
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default label for the autogenerated response "Reset". This response
// has many uses and is most likely to be overwritten on a per-script basis.
// As such, the command to activate it, dlg_ActivateResetResponse(), has an
// optional parameter to override the default. dlg_DeactivateResetResponse(),
// will turn off the reset response.
//
const string DLG_DEFAULTLABEL_RESET = "Reset";
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default label for the autogenerated response "End". This response is
// an automatic ending of the script. This is usually "goodbye" for speech or
// "Leave <object>" for an action. This response however can be lengthy but
// should convey an end to the conversation. dlg_ActivateEndResponse() turns
// on the autogenerated response and takes an optional string to override this
// default.
//
const string DLG_DEFAULTLABEL_END = "End Dialog";
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default label for the autogenerated response "Continue". This response
// is an continuation of a long dialog with little or no interaction from the
// player. The label can be changed each OnContinue if desired.
//
const string DLG_DEFAULTLABEL_CONTINUE = "Continue";
//
////////////////////////////////////////////////////////////////////////////////

// DEFAULT CUSTOM LABELS FOR AUTOGENERATED RESPONSES - END

////////////////////////////////////////////////////////////////////////////////
//  The default setting for changing the maximum responses displayed, including
// autogenerated responses. Note that to override this value you must call
// dlg_SetMaximumResponses() with a value between 5 and 15, for each dialog you
// wish to override.
//
const int DLG_DEFAULT_MAX_RESPONSES = 15;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for talking responses. dlg_AddResponseTalk() uses this
// color to display the response.
//
const string DLG_DEFAULT_TXT_TALK_COLOR = COLOR_DEFAULT;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for action responses. dlg_AddResponseAction() uses this
// color to display the response.
//
const string DLG_DEFAULT_TXT_ACTION_COLOR = COLOR_TURQUOISE;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for the autogenerated response "Next Page".
//
const string DLG_DEFAULT_TXT_NEXT_COLOR = COLOR_BLUE_LIGHT;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for the autogenerated response "Previous Page".
//
const string DLG_DEFAULT_TXT_PREVIOUS_COLOR = COLOR_BLUE_LIGHT;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for the autogenerated response "Reset".
// dlg_ActivateResetResponse() uses this color to display the response.
//
const string DLG_DEFAULT_TXT_RESET_COLOR = COLOR_YELLOW;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for the autogenerated response "End".
// dlg_ActivateEndResponse() uses this color to display the response.
//
const string DLG_DEFAULT_TXT_END_COLOR = COLOR_RED;
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//  The default color for the autogenerated response "Continue".
// dlg_ChangeLabelContinue() uses this color to display the response.
//
const string DLG_DEFAULT_TXT_CONTINUE_COLOR = COLOR_GREEN_DARK;
//
////////////////////////////////////////////////////////////////////////////////
